Repository skebobteam/datetime, pull requests merged in 2025-07, with the labels that each got.

#14 Конструкторы
  include/DateTime.h
  src/DateTime.cpp
  tests/tests.cpp
Labels: enhancement

#15 Статический метод проверки на равенство двух объектов класса
  include/DateTime.h
  src/DateTime.cpp
  tests/tests.cpp
Labels: enhancement

#18 Метод, позволяющий добавить к дате N дней
  include/DateTime.h
  src/DateTime.cpp
  tests/tests.cpp
Labels: enhancement

#21 Типы исключений
  include/DateTime.h
  src/DateTime.cpp
  tests/tests.cpp
Labels: bug, enhancement

#24 Метод, позволяющий добавить к дате M месяцев
  include/DateTime.h
  src/DateTime.cpp
  tests/tests.cpp
Labels: enhancement

#28 Класс DateTime и Интерфейс (CLI)
  include/DateTime.h
  src/DateTime.cpp
  src/main.cpp
  tests/tests.cpp
Labels: enhancement

#30 Исправление работы функции GetNameOfDayOfWeek
  include/DateTime.h
  src/DateTime.cpp
  src/main.cpp
  tests/tests.cpp
Labels: bug
